### PR TITLE
Truncate nested properties to first level as part of @each dependent …

### PR DESCRIPTION
**Pull request by cah-briangantzler**
This fixes issue https://github.com/miguelcobain/ember-yeti-table/issues/109 as discussed by truncating to first property

### CODE REVIEW

**Comment by cah-briangantzler** [comment]
Any idea when you might be able to get a look at this?

**Comment by miguelcobain** [comment]
@cah-briangantzler can you give me push access to your branch? (or create a new PR with a different branch to which I can have access)

I fixed tests on beta and canary and successfully asserted that no deprecations are thrown and also a couple of minor fixes. Wanted to get them out on this PR.

**Comment by miguelcobain** [comment]
Published on `v1.0.1`. Thanks!

**Comment by cah-briangantzler** [comment]
Interesting on the `assert.expectNoDeprecation();`   The other changes Im assuming were linting, is that saying that A() is going to be a linting error in the future?

**Comment by miguelcobain** [comment]
`assert.expectNoDeprecation();` com from the `ember-qunit-assert-helpers` addon.

Removing Ember.A was part of the fix for the tests on ember-beta.
For some reason still unknown to me, they failed on beta and canary for something related with "updating a value after accessing it in the same calculation". Something like that.

Since I didn't need tracking, I thought about not using Ember.A at all and all tests passed.
🤷‍♂️

**Pull request closed without merging**
