### PR TITLE
Updated docs for 3.16+ compatibility, removed unneeded polyfills as a result

### PR DESCRIPTION
**Pull request by cah-briangantzler**
Co-location of templates was released in Octane 3.14, so the next LTS 3.16 was chosen as the supported version +

https://github.com/miguelcobain/ember-yeti-table/issues/344

### CODE REVIEW

**Comment by cah-briangantzler** [comment]
The failing tests on Canary are because there are now deprecations in canary we can not yet fix. But because a couple of the tests actually assert that there are no deprecations, the canary build fails

**Comment by cah-briangantzler** [comment]
I am so use to using yarn. Sorry, you using npm then? will add the yarn.lock to .gitingore so I dont have to remember all the time. 

The failing tests are on canary (which is listed a . What would be the version for that? Hmm, maybe Ill do less than 3.24? The canary build is marked as allow failure https://github.com/miguelcobain/ember-yeti-table/blob/master/.github/workflows/ci.yml#L144 for this reason right? To not have to alter the tests

**Comment by miguelcobain** [comment]
They are marked to allow failure because canary builds are unstable and can fail. Still good to know if something will break in the future.

I guess `gte('3.25') ? skip : test` should work, no?

Actually, since we're eventually doing a major bump anyway, I think we should remove the deprecations entirely.

**Comment by cah-briangantzler** [comment]
If you are ok with that, I will remove the deprecated code and deprecation tests, will just be cleaner

**Comment by cah-briangantzler** [comment]
I wasnt sure if canary was given the actual next number or some placeholder like the word canary

**Comment by miguelcobain** [comment]
@cah-briangantzler let's remove the deprecation and the deprecated code, please.

**Comment by cah-briangantzler** [comment]
:) Saw there was one assert to remove. Will fix it in the next PR

**Pull request merged**
