### PR TITLE
Allows for column filtering in the header

### PR DESCRIPTION
**Pull request by bgantzler**
DO NOT MERGE

There is currently a bug in addon docs I submitted (https://github.com/ember-learn/ember-cli-addon-docs/issues/292) that prevents the docs from being created.

This pull request restructures the header and allows for the filters to be placed in the header as well as supplying a default input filter (no need for user to reinvent unless they want to use some special component). (A checkbox and select could also be provided in future)

Due to the fact that thead is tightly coupled with the tr in the header component, I had to specify a property (columnFilter) to the header to switch the structure. While this provides for backward compatibility, it would be nicer if the new structure was the default html.

While waiting on the add on docs to be created, could you look over this and provide any guidance where you might want changes. 

Thanks

### CODE REVIEW

**Comment by miguelcobain** [comment]
Ideally the `<table.header as |header|>` component would be smart enough to "switch modes" between "tr-wrapping" and "not tr-wrapping" modes.

tr-wrapping mode should be turned on when `<header.column>` was used and turned off otherwise.
I might be able to come up with something like this, but not sure if it would work due to backtrack rendering errors (since we're changing a parent element based on children rendering).

**Comment by cah-briangantzler** [comment]
To your points

- The filter column yields appropriately that any complex component could be used as the filter. Once I did this and found I had basically copied your example, I figured why should everyone copy and create the exact same boilerplate input, so I just provided the input already linked to the correct column filter property.  I also had a select as a component, that would allow you to specify the options or build them as a unique list from the column data values, but chose not to include it at this time due to increasing the api surface too much at once (which you noted in your third point)

Below is taken from the tests and while it is an input within the yielded portion, any complex component could be used in its place.
```
   <header.filters @placeholder="Search me" as |filters|>
        <filters.column @placeholder="Search on first name"/>
        <filters.column as |filterColumn|>
                <input
                  class="input" type="search" placeholder={{filterColumn.placeholder}}
                  value={{filterColumn.column.filter}}
                  oninput={{action (mut filterColumn.column.filter) value="target.value"}}>
        </filters.column>
        <filters.column/>
    </header.filters>
```
- You actually can use the filters component to provide a x number of rows, although the name doesn't exactly say that. I avoided naming the component row (although I would have preferred that) because it was yielding placeholder which was more dedicated to filter than just another row in the header. Although if there was not a global placeholder (default) but it would have to be specified at each filter column, row would work and I would vote for that.
- Any additional components of course increase the api surface, but row for the header would give much more control. I suppose a yeti-table-filters addon that provided input, select, checkbox etc might might a nice companion if you didn't want to include them in this addon. 

A checkbox filter is actually a hard one because you would want a tri-state and since HTML doesn't provide for that, you would have to custom create one, or depend on another addon that provided such a checkbox component.    


As for the mode switching, I had thought about attempting what you said, but it seemed to be a double render just waiting to happen, and preferably the row component should just be added as the standard and the current deprecated in some way. Its just one more component and with and without filters would be coded the same way, not having to learn when one is available and one is not (reducing the over all api surface and learning)


More than willing to refactor the pull request as you see fit.

**Comment by cah-briangantzler** [comment]
Renaming columns and filters to row would also avoid the bug I found in addon-docs, although it nice to have found it and get it fixed before someone else stumbles upon it.

**Comment by cah-briangantzler** [comment]
Suggestion. Create a headers component supporting the new way, leave header the old way, yield both. Hence 1 header or multiple headers. Can eventually deprecate header some the same thing can be achieved through headers, just use one row.

**Comment by miguelcobain** [comment]
Would something like this be too weird if it was properly documented?
This would work today, without any changes.

```hbs
<YetiTable @data={{data}} as |table|>

  <thead>
    <table.header @tagName="" as |header|>
	  <row.column @prop="firstName">
        First name
	  </row.column>
	  <row.column @prop="lastName">
  	    Last name
	  </row.column>
	  <row.column @prop="points">
	    Points
	  </row.column>
    </table.header>
    <tr>
      {{!-- can also use a normal <tr> --}}
    </tr>
  </thead>

  <table.body/>

</YetiTable>
```

**Comment by cah-briangantzler** [comment]
If you actually look at my issue https://github.com/miguelcobain/ember-yeti-table/issues/14, I had that already. I didnt like having to have the knowledge to do tagName='' and the thead yourself outside. Then you do a tr for the additional rows, but not the first one. 

While that does work today unchanged, you could easily break this when attempting to add any additional features

**Comment by miguelcobain** [comment]
@cah-briangantzler i see.

What would the api of your previous suggestion look like?

**Comment by cah-briangantzler** [comment]
While coding this I realized a fundamental problem. Column registers itself with the parent. We want that to happen on the column definitions, and NOT the successive columns requiring some property to designate the column definitions vs the additional rows.

Could be done through a property on the row, or yielding a columnDefinition and a column component. ColumnDefinition would be used for the header row and column for any additional rows.

No matter how you look at it, you need to know which is which. I thought about using the prop existence as the designator, but you allow for prop being optional.

(As a side note. I absolutely love the syntax over defining the columns in js. However implementing column drag and drop for reordering the columns would impossible because order is enforced in the html)

```
<YetiTable @data={{data}} as |table|>

        <table.headers as |headers|>
          <headers.row as |row|>
            <row.column @prop="firstName" data-column="test-column">
              First name
            </row.column>
            <row.column @prop="lastName">
              Last name
            </row.column>
            <row.column @visible={{visibleTest}} @prop="points">
              Points
            </row.column>
          </headers.row>
          
          <headers.row as |row|>
            <row.column as |filterColumn|>
                <input
                  class="input" type="search" placeholder="Search first name"
                  value={{filterColumn.column.filter}}
                  oninput={{action (mut filterColumn.column.filter) value="target.value"}}>
            </row.column>
            <row.column as |filterColumn|>
                <input
                  class="input" type="search" placeholder="Search last name"
                  value={{filterColumn.column.filter}}
                  oninput={{action (mut filterColumn.column.filter) value="target.value"}}>
            </row.column>
            <row.column as |filterColumn|>
                <input
                  class="input" type="search" placeholder="Search points"
                  value={{filterColumn.column.filter}}
                  oninput={{action (mut filterColumn.column.filter) value="target.value"}}>
            </row.column>
          </headers.row>
          
        </table.headers>

        <table.body/>

      </YetiTable>
```

**Comment by cah-briangantzler** [comment]
Another reason header row needs to be defined different than additional rows is the html embedded in the column component. Its very dedicated to a specific purpose.

I guess that's why I went with filters and columns in the original request, each has distinct needs

```
{{#if visible}}
  <th
    role={{if sortable "button"}}
    class="{{class}} {{if sortable "yeti-table-sortable"}} {{if isSorted "yeti-table-sorted"}} {{if isAscSorted "yeti-table-sorted-asc"}} {{if isDescSorted "yeti-table-sorted-desc"}}"
    onclick={{if sortable (action onClick this)}}
    ...attributes>
    {{yield (hash
      isSorted=isSorted
      isAscSorted=isAscSorted
      isDescSorted=isDescSorted
    )}}
  </th>
{{/if}}
```

**Comment by cah-briangantzler** [comment]
I have this working. The definition property (or any name you want) has to be on the additional rows for backward compatibility. Or two components could be yielded rowHeaders and row. Knowing which component to use isnt too different than remembering to false a property on the other rows (Note nothing prevented the filters from being the first row if desired).

A custom component could easily be provided by the user for the input field to avoid the boilerplate code. (From another addon or a provided default from this one)

```
      <YetiTable @data={{data}} as |table|>

        <table.headers as |headers|>
          <headers.row as |row|>
            <row.column @prop="firstName" @filter={{firstNameFilter}} data-column="test-column">
              First name
            </row.column>
            <row.column @prop="lastName" @filter={{lastNameFilter}}>
              Last name
            </row.column>
            <row.column @visible={{visibleTest}} @prop="points" @filter={{pointsFilter}}>
              Points
            </row.column>
          </headers.row>
          
          <headers.row @definition={{false}} as |row|>
            <row.column>
                <input
                  class="input" type="search" placeholder="Search first name"
                  value={{firstNameFilter}}
                  oninput={{action (mut firstNameFilter) value="target.value"}}>
            </row.column>
            <row.column as |filterColumn|>
                <input
                  class="input" type="search" placeholder="Search last name"
                  value={{lastNameFilter}}
                  oninput={{action (mut lastNameFilter) value="target.value"}}>
            </row.column>
            <row.column as |filterColumn|>
                <input
                  class="input" type="search" placeholder="Search points"
                  value={{pointsFilter}}
                  oninput={{action (mut pointsFilter) value="target.value"}}>
            </row.column>
          </headers.row>
          
        </table.headers>

        <table.body/>

      </YetiTable>
```

**Comment by miguelcobain** [comment]
I think I have an idea:

```hbs
<YetiTable @data={{data}} as |table|>

  <table.header as |header|>
	<header.column @prop="firstName">
	  First name
	</header.column>
	<header.column @prop="lastName">
	  Last name
	</header.column>
	<header.column @prop="points">
	  Points
	</header.column>

    <header.row>
      {{!-- render the filters here --}}
    </header.row>
    <header.row>
      {{!-- any number of rows are supported --}}
    </header.row>
  </table.header>

  <table.body/>

</YetiTable>
```

The new component here is the `<header.row>`. That component would render *outside* of the parent's `<tr>` using `{{#in-element` (ideally using [ember-in-element-polyfill](https://github.com/kaliber5/ember-in-element-polyfill)). `<table.header>` should render a document fragment outside of its <tr> and that would be where in-element would render to.

Since `{{#in-element` appends DOM, it should work with any number of `<header.row>`s.
Since `<header.row>` is the only new thing introduced, this would be both backwards compatible and with minimal new concepts to learn.

The only downside is that it might feel weird to some to not have the columns wrapped inside a `<header.row>` and have them directly descendant of a `<table.header>`. But I think that's a good tradeoff for a minor version bump.

What do you think?

**Comment by cah-briangantzler** [comment]
It seems like some trickery to avoid deprecating one component in favor of another. What would this add to the actual complexity of the code maintained? I would have to implement this to see the full effect on the code complexity.

While I was looking at the code, I realized if the user entered the td them self, instead of column, you can avoid the double registering. I would prefer going forward that the html look and make sense as the component evolves. Yielding the header component provides backward compatibility, in addition yielding the headers component allows evolution with html that looks correct.

How about this, current html works as defined by still yielding header, new component headers. Deprecate header, encourage headers.

I left column on headers to indicate it was a headers concern, not an individual row concern.

Normal table no filters or additional rows. Headers and Row is a new component, but it makes sense that the columns are just standing alone.
```
<YetiTable @data={{data}} as |table|>

        <table.headers as |headers|>
          <headers.row>
            <headers.column @prop="firstName" @filter={{firstNameFilter}} data-column="test-column">
              First name
            </headers.column>
            <headers.column @prop="lastName" @filter={{lastNameFilter}}>
              Last name
            </headers.column>
            <row.column @visible={{visibleTest}} @prop="points" @filter={{pointsFilter}}>
              Points
            </headers.column>
          </headers.row>
                    
        </table.headers>

        <table.body/>

      </YetiTable>
```

Usage with additional rows. Headers and Row still only new component. No additional properties to be set to make it work. Html looks and makes sense. One might ask why td does not have a component equivalent like column in the first row, but I think the answer is it doesnt need one, so why complicate it with an additional component. Using td raw avoids the double register problem.
```
<YetiTable @data={{data}} as |table|>

        <table.headers as |headers|>
          <headers.row>
            <headers.column @prop="firstName" @filter={{firstNameFilter}} data-column="test-column">
              First name
            </headers.column>
            <headers.column @prop="lastName" @filter={{lastNameFilter}}>
              Last name
            </headers.column>
            <headers.column @visible={{visibleTest}} @prop="points" @filter={{pointsFilter}}>
              Points
            </headers.column>
          </headers.row>
          
          <headers.row>
            <td>
                <input
                  class="input" type="search" placeholder="Search first name"
                  value={{firstNameFilter}}
                  oninput={{action (mut firstNameFilter) value="target.value"}}>
            </td>
            <td>
                <input
                  class="input" type="search" placeholder="Search last name"
                  value={{lastNameFilter}}
                  oninput={{action (mut lastNameFilter) value="target.value"}}>
            </td>
            <td>
                <input
                  class="input" type="search" placeholder="Search points"
                  value={{pointsFilter}}
                  oninput={{action (mut pointsFilter) value="target.value"}}>
            </td>
          </headers.row>
          
        </table.headers>

        <table.body/>

      </YetiTable>
```

Easy to remove header component as a yielded component when that syntax is no longer needed to be supported.

But in the end, its your call, and Im cool with that. So looks like we have two suggestions, which would you like to do?

**Comment by miguelcobain** [comment]
@cah-briangantzler just to be clear, you're proposing a new `<table.headers>` (plural) that basically does not wrap any <tr>. But the currently existing `<table.header>` would continue to work, right?

Perhaps a more future proof name would be `head` (just like ember-table does)?

If so, we could even suggest names that resemble html tables like:

```hbs
<YetiTable @data={{data}} as |t|>

  <t.head as |h|>
</YetiTable>
```

**Comment by cah-briangantzler** [comment]
Yes that is what I am suggesting, headers as plural although head is perfectly acceptable. Yes header will still continue to work until deprecated and removed.

**Comment by miguelcobain** [comment]
@cah-briangantzler thanks a lot for the insightful suggestions and thought process!
I agree with what you came up with.

Are you willing to work on this?

**Comment by cah-briangantzler** [comment]
Working on it now. I have it all coded which is how I'm finding the problems.

Problem now is in the below, since the th is raw and NOT a component, it is not hidden when the column is hidden.  Assuming the answer is replacing the th with a another component, cell perhaps to stay in line with the body.

Sorry for all the back and forth, but the example of having the filtering at the bottom of the table just doesn't feel right.

```
<YetiTable @data={{data}} as |table|>

        <table.head as |head|>
          <head.row>
            <head.column @prop="firstName" @filter={{firstNameFilter}} data-column="test-column">
              First name
            </head.column>
            <head.column @prop="lastName" @filter={{lastNameFilter}}>
              Last name
            </head.column>
            <head.column @visible={{visibleTest}} @prop="points" @filter={{pointsFilter}}>
              Points
            </head.column>
          </head.row>
          
          <head.row>
            <th>
                <input
                  class="input" type="search" placeholder="Search first name"
                  value={{firstNameFilter}}
                  oninput={{action (mut firstNameFilter) value="target.value"}}>
            </th>
            <th>
                <input
                  class="input" type="search" placeholder="Search last name"
                  value={{lastNameFilter}}
                  oninput={{action (mut lastNameFilter) value="target.value"}}>
            </th>
            <th>
                <input
                  class="input" type="search" placeholder="Search points"
                  value={{pointsFilter}}
                  oninput={{action (mut pointsFilter) value="target.value"}}>
            </th>
          </head.row>
          
        </table.head>

        <table.body/>

      </YetiTable>
```

If we yielded cell from row, with this format, column should also be yielded from row. We can't reuse column because of the registration so forced to have another component, cell. Or cell could be yielded from head, but that just seems to break the hierarchy



So do you wish (row, column, cell yielded from head)
```
<YetiTable @data={{data}} as |table|>
        <table.head as |head|>
          <head.row>
            <head.column @prop="firstName" @filter={{firstNameFilter}} data-column="test-column">
              First name
            </headers.column>
          </headers.row>
          
          <head.row>
            <head.cell>
                <input
                  class="input" type="search" placeholder="Search first name"
                  value={{firstNameFilter}}
                  oninput={{action (mut firstNameFilter) value="target.value"}}>
            </head.cell>
          </head.row>
          
        </table.head>

        <table.body/>

      </YetiTable>
```

Or (row from head, column, cell from row) (my preference)
```
<YetiTable @data={{data}} as |table|>
        <table.head as |head|>
          <head.row as |row|>
            <row.column @prop="firstName" @filter={{firstNameFilter}} data-column="test-column">
              First name
            </row.column>
          </head.row>
          
          <head.row as |row|>
            <row.cell>
                <input
                  class="input" type="search" placeholder="Search first name"
                  value={{firstNameFilter}}
                  oninput={{action (mut firstNameFilter) value="target.value"}}>
            </row.cell>
          </head.row>
          
        </table.head>

        <table.body/>

      </YetiTable>
```

**Comment by miguelcobain** [comment]
@cah-briangantzler ah, nice catch.

I believe that yielding cell from row, as you suggest, makes more sense.
It also aligns better with how we are already yielding cell from body.

Also having both `row.column` and `row.cell` kind of conveys that they are indeed different. The name "column" sounds like something more general that affects the whole table.

Thanks again for working on this. 👍

**Comment by cah-briangantzler** [comment]
Ok, got it all working. Now to adjust the documentation. Will need help on that, not sure how you want to document deprecating header in favor of head.

None of the components end in s, so the addon docs isnt a problem now. (Have to get to a pull request for that as well)

**Comment by cah-briangantzler** [comment]
That's fine, there is no need to deprecate header, so yea, adjust the docs accordingly. Even with the single header use case, I personally would use the new syntax always, makes adding another row later that much more straightforward.

Working on the docs now, but may take a short break, so may be later or tomorrow. In EST

**Comment by cah-briangantzler** [comment]
I have all that I was going to do complete. You can check it and see if you need anything changed. I am unsure as to why 2.16 and 2.18 fail for the ...attributes if they didnt fail before. I do not believe anytthing I have done should have affected those tests.

**Comment by cah-briangantzler** [comment]
Havent heard from you in a while. Realize it is Holidays. Hope to hear some time early next year

**Comment by miguelcobain** [comment]
@cah-briangantzler @bgantzler The only thing I'm not so sure is the `head/row/cell` component yielding the entire column.
That column is a full column component instance, so I feel that's a little too "broad" api and people might use it in unexpected ways.

I'd be more confident in yielding just what is needed, or ideally nothing at all (the `body/row/cell` component doesn't yield anything as well).

So, your example of filtering in the header would become similar to the already existing example on the footer:

```
<YetiTable @data={{data}} as |table|>

  <table.head as |head|>
    <head.row as |row|>
      <row.column @prop="firstName" data-column="test-column">
        First name
      </row.column>
      <row.column @prop="lastName">
        Last name
      </row.column>
      <row.column @visible={{visibleTest}} @prop="points" @filter={{pointsFilter}}>
        Points
      </row.column>
    </head.row>
          
    <head.row as |row|>
      <row.cell>
        <input
          class="input" type="search" placeholder="Search first name"
          value={{firstNameFilter}}
          oninput={{action (mut firstNameFilter) value="target.value"}}>
      </row.cell>
      <row.cell>
        <input
          class="input" type="search" placeholder="Search last name"
          value={{lastNameFilter}}
          oninput={{action (mut lastNameFilter) value="target.value"}}>
      </row.cell>
      <row.cell>
        <input
          class="input" type="search" placeholder="Search points"
          value={{pointsFilter}}
          oninput={{action (mut pointsFilter) value="target.value"}}>
      </row.cell>
    </head.row>
       
    </table.head>

  <table.body/>

</YetiTable>
```

This would delegate the responsibility of holding the necessary state to the user, and I feel it's more in line with the rest of the api and less risky. 
If we yield component instances there's no turning back without breaking changes if we later implement this thing in a different way. Also, no possibility of doing weird stuff with the column component instance.

----

Another thing is that now I feel like we need a new identical `<t.foot as |foot|>`, `<foot.row as |row|>` and `<row.cell>` components to deal with the same column visibility issue we had on the `<t.head>` case.


Would you be opposed to these changes? I wanted to get your input before actually doing it, but I like how the whole flexibility and naming ended up. Thanks again.

**Comment by cah-briangantzler** [comment]
Made all the changes as requested.

Updated the docs where you show pagination to use the new table.foot component over raw tfoot usages.

In the styling section of the docs below where it shows pagination outside the table, it shows pagination in the footer with a colspan. This is the same code as displayed under the pagination section and probably should not be repeated here.

**Comment by cah-briangantzler** [comment]
Would like to start using the head and foot options. Any idea when this might be able to be merged?

**Comment by miguelcobain** [comment]
@cah-briangantzler thanks again for being the champion for this nice features. 
Cheers!

**Comment by cah-briangantzler** [comment]
I saw your cleanup, looks like I left you a little more to fix than I thought I had. Sorry about that.

**Pull request merged**
